
import { Menu } from "@/components/menu"

import { Sidebar } from "@/components/sidebar"


import Head from "next/head";

export default function Layout({children}:{children:React.ReactNode}){

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hidden md:block">
        <Menu />
        <div className="border-t">
          <div className="bg-background">
            <div className="grid lg:grid-cols-5">
              <Sidebar className="hidden lg:block" />
              <div className="col-span-3 lg:col-span-4 lg:border-l">
                {children}
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  

    
  );
}



